application: songkhla-1291
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /
  script: index.php
- url: /(.*\.(gif|png|jpg|ico|js|css|eot|svg|ttf|woff|woff2))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|eot|svg|ttf|woff|woff2))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt

- url: .*
  script: main.py
